version: '3'
services:

  # mysql
  mysql:
    image: "mysql:5.7.10"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "nodeblog"

  server:
    build: ./server/
    container_name: "typeorm-server"
    ports:
      - "5000:5000"
    depends_on:
      - "mysql"